using System.Collections.Generic;

namespace Helpers
{
    public static class BricklinkColorMap
    {
        // Bricklink ColorId -> interne Farbnamen (wie in BrickColor.Name)
        private static readonly Dictionary<int, string> _bricklinkIdToName = new()
        {
            { 0, "Black" },
            { 1, "Blue" },
            { 2, "Green" },
            { 3, "Dark Turquoise" },
            { 4, "Red" },
            { 5, "Dark Pink" },
            { 6, "Brown" },
            { 7, "Light Gray" },
            { 8, "Dark Gray" },
            { 9, "Light Blue" },
            { 10, "Bright Green" },
            { 11, "Dark Orange" },
            { 12, "Light Green" },
            { 13, "Tan" },
            { 14, "Yellow" },
            { 15, "White" },
            { 17, "Light Pink" },
            { 18, "Light Yellow" },
            { 19, "Light Purple" },
            { 20, "Purple" },
            { 21, "Light Orange" },
            { 22, "Orange" },
            { 23, "Magenta" },
            { 25, "Lime" },
            { 26, "Pink" },
            { 27, "Light Brown" },
            { 28, "Dark Blue" },
            { 29, "Dark Green" },
            { 30, "Light Aqua" },
            { 31, "Aqua" },
            { 32, "Light Red" },
            { 33, "Medium Blue" },
            { 34, "Medium Green" },
            { 35, "Medium Orange" },
            { 36, "Medium Violet" },
            { 37, "Medium Yellow" },
            { 38, "Medium Pink" },
            { 39, "Medium Brown" },
            { 40, "Medium Gray" },
            { 41, "Medium Tan" },
            { 42, "Medium White" },
            { 43, "Medium Red" },
            { 44, "Medium Magenta" },
            { 45, "Medium Lime" },
            { 46, "Medium Aqua" },
            { 47, "Medium Blue-Violet" },
            { 48, "Medium Orange-Yellow" },
            { 49, "Medium Green-Yellow" },
            { 50, "Medium Blue-Green" },
            { 51, "Medium Red-Violet" },
            { 52, "Medium Yellow-Green" },
            { 54, "Dark Red" },
            { 55, "Dark Blue-Violet" },
            { 56, "Dark Orange-Yellow" },
            { 57, "Dark Yellow" },
            { 58, "Dark Green-Yellow" },
            { 59, "Dark Blue-Green" },
            { 60, "Dark Red-Violet" },
            { 61, "Dark Yellow-Green" },
            { 62, "Dark Blue-Green" },
            { 63, "Dark Red-Brown" },
            { 64, "Dark Blue-Gray" },
            { 65, "Dark Green-Gray" },
            { 66, "Dark Yellow-Gray" },
            { 67, "Dark Red-Gray" },
            { 68, "Reddish Brown" },
            { 69, "Light Bluish Gray" },
            { 70, "Dark Bluish Gray" },
            { 71, "Bright Light Orange" },
            { 72, "Bright Light Blue" },
            { 73, "Bright Light Yellow" },
            { 74, "Bright Light Green" },
            { 75, "Bright Light Pink" },
            { 76, "Bright Light Violet" },
            { 77, "Bright Light Red" },
            { 78, "Bright Light Brown" },
            { 79, "Bright Light Gray" },
            { 80, "Bright Light Tan" },
            { 81, "Bright Light White" },
            { 82, "Bright Light Magenta" },
            { 83, "Bright Light Lime" },
            { 84, "Bright Light Aqua" },
            { 85, "Dark Tan" },
            { 86, "Sand Blue" },
            { 87, "Sand Green" },
            { 88, "Sand Yellow" },
            { 89, "Sand Red" },
            { 90, "Sand Purple" },
            { 91, "Sand Orange" },
            { 92, "Sand Pink" },
            { 93, "Sand White" },
            { 94, "Sand Magenta" },
            { 95, "Sand Lime" },
            { 96, "Sand Aqua" },
            { 97, "Sand Blue-Violet" },
            { 98, "Sand Orange-Yellow" },
            { 99, "Sand Green-Yellow" },
            { 100, "Sand Blue-Green" },
            { 101, "Sand Red-Violet" },
            { 102, "Sand Yellow-Green" },
            { 110, "Trans-Clear" },
            { 111, "Trans-Black" },
            { 112, "Trans-Red" },
            { 113, "Trans-Green" },
            { 114, "Trans-Blue" },
            { 115, "Trans-Yellow" },
            { 116, "Trans-Purple" },
            { 117, "Trans-Pink" },
            { 118, "Trans-Orange" },
            { 119, "Trans-Brown" },
            { 120, "Trans-Light Blue" },
            { 121, "Trans-Light Green" },
            { 122, "Trans-Light Yellow" },
            { 123, "Trans-Light Pink" },
            { 124, "Trans-Light Violet" },
            { 125, "Trans-Light Red" },
            { 126, "Trans-Light Brown" },
            { 127, "Trans-Light Gray" },
            { 128, "Trans-Light Tan" },
            { 129, "Trans-Light White" },
            { 130, "Trans-Light Magenta" },
            { 131, "Trans-Light Lime" },
            { 132, "Trans-Light Aqua" },
            { 133, "Trans-Light Blue-Violet" },
            { 134, "Trans-Light Orange-Yellow" },
            { 135, "Trans-Light Green-Yellow" },
            { 136, "Trans-Light Blue-Green" },
            { 137, "Trans-Light Red-Violet" },
            { 138, "Trans-Light Yellow-Green" },
            // ... weitere Farben nach Bedarf
        };

        public static string? GetBrickColorName(int bricklinkColorId)
        {
            return _bricklinkIdToName.TryGetValue(bricklinkColorId, out var name) ? name : null;
        }
    }
}
