// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using brickapp.Data;

#nullable disable

namespace brickapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219092352_addSourceToWantedList")]
    partial class addSourceToWantedList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItemSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetNum")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("itemsets", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAdmin = true,
                            Name = "Admin",
                            Uuid = "111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAdmin = false,
                            Name = "Uwe",
                            Uuid = "222"
                        });
                });

            modelBuilder.Entity("brickapp.Data.Entities.BrickColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BricklinkColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RebrickableColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Rgb")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrickColorId")
                        .HasColumnType("integer");

                    b.Property<int>("MappedBrickId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("MappedBrickId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.ItemSetBrick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrickColorId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemSetId")
                        .HasColumnType("integer");

                    b.Property<int>("MappedBrickId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("ItemSetId");

                    b.HasIndex("MappedBrickId");

                    b.ToTable("itemsetbricks", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.MappedBrick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BluebrixxName")
                        .HasColumnType("text");

                    b.Property<string>("BluebrixxPartNum")
                        .HasColumnType("text");

                    b.Property<string>("CadaName")
                        .HasColumnType("text");

                    b.Property<string>("CadaPartNum")
                        .HasColumnType("text");

                    b.Property<bool>("HasAtLeastOneMapping")
                        .HasColumnType("boolean");

                    b.Property<string>("LegoName")
                        .HasColumnType("text");

                    b.Property<string>("LegoPartNum")
                        .HasColumnType("text");

                    b.Property<string>("MouldKingName")
                        .HasColumnType("text");

                    b.Property<string>("MouldKingPartNum")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PantasyName")
                        .HasColumnType("text");

                    b.Property<string>("PantasyPartNum")
                        .HasColumnType("text");

                    b.Property<string>("UnknownName")
                        .HasColumnType("text");

                    b.Property<string>("UnknownPartNum")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mappedBricks", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.MappingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrickId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MappingItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MappingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BrickId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("mappingRequests", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.MissingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExternalColorId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalPartNum")
                        .HasColumnType("text");

                    b.Property<int?>("MockId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("WantedListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MockId");

                    b.HasIndex("WantedListId");

                    b.ToTable("MissingItem");
                });

            modelBuilder.Entity("brickapp.Data.Entities.Mock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MockType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebSource")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserUuid");

                    b.ToTable("mocks", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.MockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrickColorId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalPartNum")
                        .HasColumnType("text");

                    b.Property<int?>("MappedBrickId")
                        .HasColumnType("integer");

                    b.Property<int>("MockId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("MappedBrickId");

                    b.HasIndex("MockId");

                    b.ToTable("mockitems", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewItemRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("newItemRequests", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewSetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("text");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("newSetRequests", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewSetRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemIdOrName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewSetRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewSetRequestId");

                    b.ToTable("newSetRequestItems", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.UserItemSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemSetId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("UserItemSetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ItemSetId");

                    b.HasIndex("UserItemSetId");

                    b.ToTable("useritemsets", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserUuid");

                    b.ToTable("userNotifications", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.WantedList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("wantedlists", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.WantedListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrickColorId")
                        .HasColumnType("integer");

                    b.Property<int>("MappedBrickId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("WantedListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("MappedBrickId");

                    b.HasIndex("WantedListId");

                    b.ToTable("wantedlistitems", (string)null);
                });

            modelBuilder.Entity("brickapp.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "AppUser")
                        .WithMany("InventoryItems")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.BrickColor", "BrickColor")
                        .WithMany("InventoryItems")
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany("InventoryItems")
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("BrickColor");

                    b.Navigation("MappedBrick");
                });

            modelBuilder.Entity("brickapp.Data.Entities.ItemSetBrick", b =>
                {
                    b.HasOne("brickapp.Data.Entities.BrickColor", "BrickColor")
                        .WithMany()
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItemSet", "ItemSet")
                        .WithMany("Bricks")
                        .HasForeignKey("ItemSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany()
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrickColor");

                    b.Navigation("ItemSet");

                    b.Navigation("MappedBrick");
                });

            modelBuilder.Entity("brickapp.Data.Entities.MappingRequest", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "ApprovedByUser")
                        .WithMany("MappingRequestsApproved")
                        .HasForeignKey("ApprovedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("brickapp.Data.Entities.MappedBrick", "Brick")
                        .WithMany("MappingRequests")
                        .HasForeignKey("BrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.AppUser", "RequestedByUser")
                        .WithMany("MappingRequestsRequested")
                        .HasForeignKey("RequestedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Brick");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("brickapp.Data.Entities.MissingItem", b =>
                {
                    b.HasOne("brickapp.Data.Entities.Mock", null)
                        .WithMany("MissingItems")
                        .HasForeignKey("MockId");

                    b.HasOne("brickapp.Data.Entities.WantedList", null)
                        .WithMany("MissingItems")
                        .HasForeignKey("WantedListId");
                });

            modelBuilder.Entity("brickapp.Data.Entities.Mock", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserUuid")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("brickapp.Data.Entities.MockItem", b =>
                {
                    b.HasOne("brickapp.Data.Entities.BrickColor", "BrickColor")
                        .WithMany()
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("brickapp.Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany()
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("brickapp.Data.Entities.Mock", "Mock")
                        .WithMany("Items")
                        .HasForeignKey("MockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrickColor");

                    b.Navigation("MappedBrick");

                    b.Navigation("Mock");
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewItemRequest", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "ApprovedByUser")
                        .WithMany("NewItemRequestsApproved")
                        .HasForeignKey("ApprovedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("brickapp.Data.Entities.AppUser", "RequestedByUser")
                        .WithMany("NewItemRequestsRequested")
                        .HasForeignKey("RequestedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewSetRequestItem", b =>
                {
                    b.HasOne("brickapp.Data.Entities.NewSetRequest", null)
                        .WithMany("Items")
                        .HasForeignKey("NewSetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("brickapp.Data.Entities.UserItemSet", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "AppUser")
                        .WithMany("UserItemSets")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemSet", "ItemSet")
                        .WithMany()
                        .HasForeignKey("ItemSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.UserItemSet", null)
                        .WithMany("UserItemSets")
                        .HasForeignKey("UserItemSetId");

                    b.Navigation("AppUser");

                    b.Navigation("ItemSet");
                });

            modelBuilder.Entity("brickapp.Data.Entities.UserNotification", b =>
                {
                    b.HasOne("brickapp.Data.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserUuid")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("brickapp.Data.Entities.WantedListItem", b =>
                {
                    b.HasOne("brickapp.Data.Entities.BrickColor", "BrickColor")
                        .WithMany()
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany()
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("brickapp.Data.Entities.WantedList", "WantedList")
                        .WithMany("Items")
                        .HasForeignKey("WantedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrickColor");

                    b.Navigation("MappedBrick");

                    b.Navigation("WantedList");
                });

            modelBuilder.Entity("ItemSet", b =>
                {
                    b.Navigation("Bricks");
                });

            modelBuilder.Entity("brickapp.Data.Entities.AppUser", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MappingRequestsApproved");

                    b.Navigation("MappingRequestsRequested");

                    b.Navigation("NewItemRequestsApproved");

                    b.Navigation("NewItemRequestsRequested");

                    b.Navigation("Notifications");

                    b.Navigation("UserItemSets");
                });

            modelBuilder.Entity("brickapp.Data.Entities.BrickColor", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("brickapp.Data.Entities.MappedBrick", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MappingRequests");
                });

            modelBuilder.Entity("brickapp.Data.Entities.Mock", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MissingItems");
                });

            modelBuilder.Entity("brickapp.Data.Entities.NewSetRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("brickapp.Data.Entities.UserItemSet", b =>
                {
                    b.Navigation("UserItemSets");
                });

            modelBuilder.Entity("brickapp.Data.Entities.WantedList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MissingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
