// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAdmin = true,
                            Name = "Admin",
                            Uuid = "111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAdmin = false,
                            Name = "Uwe",
                            Uuid = "222"
                        });
                });

            modelBuilder.Entity("Data.Entities.BrickColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RebrickableColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rgb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrickColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MappedBrickId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("MappedBrickId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ItemSetBrick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrickColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MappedBrickId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("ItemSetId");

                    b.HasIndex("MappedBrickId");

                    b.ToTable("itemsetbricks", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MappedBrick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BbName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BbPartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("CadaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CadaPartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegoName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegoPartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("MouldKingName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MouldKingPartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PantasyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PantasyPartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnknownName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnknownPartNum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("mappedBricks", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MappingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrickId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BrickId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("mappingRequests", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Mock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MockImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MockType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSource")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUuid");

                    b.ToTable("mocks", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrickColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalPartNum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MappedBrickId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrickColorId");

                    b.HasIndex("MappedBrickId");

                    b.HasIndex("MockId");

                    b.ToTable("mockitems", (string)null);
                });

            modelBuilder.Entity("Data.Entities.NewItemRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("newItemRequests", (string)null);
                });

            modelBuilder.Entity("Data.Entities.NewSetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonRejected")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("newSetRequests", (string)null);
                });

            modelBuilder.Entity("Data.Entities.NewSetRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdOrName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewSetRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewSetRequestId");

                    b.ToTable("newSetRequestItems", (string)null);
                });

            modelBuilder.Entity("Data.Entities.UserItemSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserItemSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ItemSetId");

                    b.HasIndex("UserItemSetId");

                    b.ToTable("useritemsets", (string)null);
                });

            modelBuilder.Entity("Data.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUuid");

                    b.ToTable("userNotifications", (string)null);
                });

            modelBuilder.Entity("ItemSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegoSetNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("itemsets", (string)null);
                });

            modelBuilder.Entity("Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "AppUser")
                        .WithMany("InventoryItems")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.BrickColor", "BrickColor")
                        .WithMany("InventoryItems")
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany("InventoryItems")
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("BrickColor");

                    b.Navigation("MappedBrick");
                });

            modelBuilder.Entity("Data.Entities.ItemSetBrick", b =>
                {
                    b.HasOne("Data.Entities.BrickColor", "BrickColor")
                        .WithMany()
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItemSet", "ItemSet")
                        .WithMany("Bricks")
                        .HasForeignKey("ItemSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany()
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrickColor");

                    b.Navigation("ItemSet");

                    b.Navigation("MappedBrick");
                });

            modelBuilder.Entity("Data.Entities.MappingRequest", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "ApprovedByUser")
                        .WithMany("MappingRequestsApproved")
                        .HasForeignKey("ApprovedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.MappedBrick", "Brick")
                        .WithMany("MappingRequests")
                        .HasForeignKey("BrickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.AppUser", "RequestedByUser")
                        .WithMany("MappingRequestsRequested")
                        .HasForeignKey("RequestedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Brick");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Data.Entities.Mock", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserUuid")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.MockItem", b =>
                {
                    b.HasOne("Data.Entities.BrickColor", "BrickColor")
                        .WithMany()
                        .HasForeignKey("BrickColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.MappedBrick", "MappedBrick")
                        .WithMany()
                        .HasForeignKey("MappedBrickId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.Mock", "Mock")
                        .WithMany("Items")
                        .HasForeignKey("MockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrickColor");

                    b.Navigation("MappedBrick");

                    b.Navigation("Mock");
                });

            modelBuilder.Entity("Data.Entities.NewItemRequest", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "ApprovedByUser")
                        .WithMany("NewItemRequestsApproved")
                        .HasForeignKey("ApprovedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.AppUser", "RequestedByUser")
                        .WithMany("NewItemRequestsRequested")
                        .HasForeignKey("RequestedByUserId")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Data.Entities.NewSetRequestItem", b =>
                {
                    b.HasOne("Data.Entities.NewSetRequest", null)
                        .WithMany("Items")
                        .HasForeignKey("NewSetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.UserItemSet", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "AppUser")
                        .WithMany("UserItemSets")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemSet", "ItemSet")
                        .WithMany()
                        .HasForeignKey("ItemSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UserItemSet", null)
                        .WithMany("UserItemSets")
                        .HasForeignKey("UserItemSetId");

                    b.Navigation("AppUser");

                    b.Navigation("ItemSet");
                });

            modelBuilder.Entity("Data.Entities.UserNotification", b =>
                {
                    b.HasOne("Data.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserUuid")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.AppUser", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MappingRequestsApproved");

                    b.Navigation("MappingRequestsRequested");

                    b.Navigation("NewItemRequestsApproved");

                    b.Navigation("NewItemRequestsRequested");

                    b.Navigation("Notifications");

                    b.Navigation("UserItemSets");
                });

            modelBuilder.Entity("Data.Entities.BrickColor", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Data.Entities.MappedBrick", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MappingRequests");
                });

            modelBuilder.Entity("Data.Entities.Mock", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Data.Entities.NewSetRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Data.Entities.UserItemSet", b =>
                {
                    b.Navigation("UserItemSets");
                });

            modelBuilder.Entity("ItemSet", b =>
                {
                    b.Navigation("Bricks");
                });
#pragma warning restore 612, 618
        }
    }
}
